### ISSUE TITLE
Which file has the list of 152 journals that reverse flipped?

### ISSUE THREAD

**Issue by rossmounce** [njahn82/rev_flip_results#1]
Which file has the list of 152 journals that reverse flip?

All of the data files I've looked at seem to be rather more complicated...
I'm just looking for a clean 'results' file containing at a minimum an ISSN number and a Journal title for each of the 152 journals that you have asserted are reverse flipped.

Most of the csv's and xslx files appear to have >200 rows of data!

**Comment by njahn82** [comment]
Hi @rossmounce  the second sheet of `data/master_list.xlsx` was used to start analysis. A clean version is also available via Zenodo:
https://doi.org/10.5281/zenodo.2553581

**Comment by rossmounce** [comment]
ah.... thanks. I didnt see that you have multiple sheets in that file. Only saw the first sheet
